#!/bin/sh
# This must be renamed to the name of the relation. The goal here is to
# affect any change needed by relationships being formed
# This script should be idempotent.
juju-log $JUJU_REMOTE_UNIT joined

juju-log Relation settings:
relation-get
juju-log Relation members:
relation-list
relation-get > /home/ubuntu/relation-data
relation-set username=sdn-agent

